---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:griffin-oly/gitops-helm
    path: charts/podinfo
    ref: master
  values:
    image: ggriffin924/podinfo:dev-cqmwl93g
    replicaCount: 1
    hpa:
      enabled: false
